#!/bin/bash

#SBATCH --job-name=Coffeejob
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=15
#SBATCH --time=48:00:00
#SBATCH --mem=30000M
#SBATCH --output=slurm_output_%A.out

module purge

cd $HOME/thesis/
source activate thesisenv

clingo --parallel-mode 15,split --models=0 --opt-mode=opt temporal_axioms.lp figurative_events.lp figurative_backbone.lp figurative_constraints.lp figurative_synthesis.lp  coffee_interpretation.lp figurative_judgements.lp input_coffee.lp > coffee_output.txt
