#!/bin/bash

#SBATCH --job-name=Figjob
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=48:00:00
#SBATCH --mem=90000M
#SBATCH --output=slurm_output_%A.out

module purge

cd $HOME/thesis/
source activate thesisenv

clingo --parallel-mode 15 --models=0 --opt-mode=opt input_leftright_9.lp temporal_axioms.lp spatial_synthesis.lp spatial_axioms.lp figurative_backbone.lp figurative_constraints.lp figurative_events.lp figurative_synthesis.lp figurative_judgements.lp > output.lp